

### Bootstrap a deploy server from your local machine!

---

- hosts: cameraman-servers

  vars:
    root_dir: "/opt/"
    home_dir: "/home/{{ansible_ssh_user}}"
    app_dir: "{{root_dir}}/headless-cameraman"
    github_private_key_file: "{{home_dir}}/github-deploy-key"

  tasks:

  - name: "Tell git to use private key for github.com access"
    template: 
      src: ../files/deploy_ssh_config.tpl 
      dest: "{{home_dir}}/.ssh/config"
      owner: "{{ansible_ssh_user}}"
    sudo: yes

  - copy: src=../../secrets/deploy-key dest={{github_private_key_file}} owner={{ansible_ssh_user}} mode=0600

  - name: "make checkout dir"
    file: 
      state: "directory"
      path: "/opt/headless-cameraman"
      owner: "{{ansible_ssh_user}}"
    sudo: yes

  - name: "Checkout 'headless-cameraman'"
    git: 
      repo: git@github.com:topher515/headless-cameraman.git
      dest: "{{app_dir}}"
      version: "HEAD"
      # accept_hostkey: true
    sudo: no

  - name: Install packages based on package.json.
    npm: path={{app_dir}}/cameraman

  - copy: src=../files/forever-production.json dest=/etc/headless-cameraman/forever.json owner={{ansible_ssh_user}} mode=0600

  - name: "Install forever (to run Node.js app)."
    npm: name=forever global=yes state=present
  
  - name: "Start example Node.js app."
    command: forever restart /etc/headless-cameraman/forever.json
    # when: "forever_list.stdout.find('/path/to/app.js') == -1"

  # - name: "Check list of Node.js apps running."
  #   command: forever list
  #   register: forever_list
  #   changed_when: false

  # - name: "Start example Node.js app."
  #   command: forever start /etc/headless-cameraman/forever.json
  #   when: "forever_list.stdout.find('/path/to/app.js') == -1"

  # - name: "Start example Node.js app."
  #   command: forever start /etc/headless-cameraman/forever.json
  #   when: "forever_list.stdout.find('/path/to/app.js') != -1"

# - name: "ensure `zoomforth_site` checked out to `{{site_version}}`"
#   git: 
#     repo: git@github.com:zoomforth/zoomforth_site.git
#     dest: "{{zoomforth_site_repo_dir}}"
#     version: "{{site_version}}"
#     accept_hostkey: true
#   sudo: no


